### ISSUE TITLE
`vue-pug/component-name-in-template-casing` not working

### ISSUE THREAD

**Issue by Rick02022** [rashfael/eslint-plugin-vue-pug#23]
I try to use `vue-pug/component-name-in-template-casing`, but not working.
However, `vue/component-name-in-template-casing` is correct.

### package version

- "eslint": "^8.53.0",
- "eslint-plugin-vue": "^9.18.1",
- "eslint-plugin-vue-pug": "^0.6.0",
- "vue-eslint-parser": "^9.3.2",
- "@typescript-eslint/eslint-plugin": "^6.9.1",
- "@typescript-eslint/parser": "^6.9.1",
- "pug": "^3.0.2",
- "pug-plain-loader": "^1.1.0",

### .eslintrc.cjs
```javascript
// @ts-check
/* eslint-env node */

module.exports = {
  root: true,

  extends: [
    // eslint rules
    'eslint:recommended',

    // vue rules
    'plugin:vue/vue3-essential',
    'plugin:vue-pug/vue3-essential',
    'plugin:vue/vue3-strongly-recommended',
    'plugin:vue-pug/vue3-strongly-recommended',
    'plugin:vue/vue3-recommended',
    'plugin:vue-pug/vue3-recommended',

    // jest rules
    'plugin:jest/recommended',

    // https://github.com/unplugin/unplugin-auto-import#eslint
    './.eslintrc-auto-import.json',

    // prettier rules (must be last)
    'plugin:prettier/recommended',
  ],

  parser: 'vue-eslint-parser',

  parserOptions: {
    parser: '@typescript-eslint/parser',
    sourceType: 'module',
  },

  plugins: ['@typescript-eslint', 'eslint-plugin-jest'],

  rules: {
    'vue-pug/component-name-in-template-casing': [
      'error',
      'PascalCase',
      { registeredComponentsOnly: true },
    ],
  },
}
```

**Comment by rashfael** [comment]
Thanks for the bug report!
There isn't a test for this rule yet. I'm going to add one, to see if we need to actually override the upstream rule, but I can already see that the problem lies with the rule fixing code, which tries to insert `<` and replacing end tags, which pug doesn't have.

**Comment by Rick02022** [comment]
Thanks for your help!
This is a simple example in my project, and it not detect wrong casing.
It always is right, all vue file have the same problem.
I hope this information is helpful to you.

```vue
<script setup="" lang="ts">
  import IconSearch from '@/presentations/components/IconSearch.vue'
</script>

<template lang="pug">
el-button(type='primary')
  el-icon
    icon-search
  span 搜尋
</template>
```

**Comment by rashfael** [comment]
Thanks for the example. I can confirm that the `vue-pug` rule does not find the incorrectly cased `icon-search` in your example and I think it has something to do with `script setup`. Defining an `IconSearch` component through the options API works. I'll investigate further and release a fix.

**Comment by rashfael** [comment]
I released v0.6.1. Can you try it out?

**Comment by Rick02022** [comment]
I try v0.6.1, `icon-search` is right to detect wrong casing, but `el-button` and `el-icon` are still no effect.
That are auto import by `unplugin-vue-components`, and I also set [Typescrip support](https://github.com/unplugin/unplugin-vue-components#typescript).

**Comment by Rick02022** [comment]
Oh, no!
I found to use `HTML` and `vue/component-name-in-template-casing` that is also wrong.
Then, `vue/component-name-in-template-casing` can effect `pug`, and `vue-pug/component-name-in-template-casing` can effect `HTML`, this shouldn't be.
Can you fix these problems?

**Comment by rashfael** [comment]
If components get auto-imported somehow and the upstream `vue/component-name-in-template-casing` also does not handle this, there is nothing much I can do. If `eslint-plugin-vue` has the same problem with html templates it would be best to open an issue there and for us to then use their code.

> Then, vue/component-name-in-template-casing can effect pug, and vue-pug/component-name-in-template-casing can effect HTML, this shouldn't be.

The way `eslint-plugin-vue-pug` works for most rules is to compile pug to html internally **before** it arrives at the rule through a [custom tokenizer](https://github.com/vuejs/vue-eslint-parser/blob/master/docs/implementing-custom-template-tokenizers.md) and then letting the normal `vue/*` rules do the rest. `eslint-plugin-vue-pug` ships a few `vue-pug/` rules where upstream rules don't work out-of-the-box, and disables others that don't apply well to pug. You can see how each upstream rule is covered and tested (or not) [here](https://github.com/rashfael/eslint-plugin-vue-pug/tree/main/docs/rules).

This means that `vue/` and `vue-pug/` rules don't differentiate between html and pug templates themselves and apply to both (for `vue-pug/` rules we probably could write a check, since we control the code, but not the other way round).

There are actually just [three `vue-pug/` rules](https://github.com/rashfael/eslint-plugin-vue-pug/tree/main/lib/rules) right now, the rest are directly from `eslint-plugin-vue`. Only like that it's even possible to provide this package, without that, it would be too much work to rewrite and maintain every rule.

I hope this explanation helps a bit.

**Comment by rashfael** [comment]
I'm going to close this issue, since I think this isn't specific to pug. If you have any new information, please reopen.
